spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:airtransport;MODE=POSTGRESQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
      path: /h2